apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-dev
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: discord-bot
        image: discord-bot
        command: ["sh", "-c", "pip install --no-cache-dir -r /app/bot.req && python3 /app/bot.py"]
        volumeMounts:
        - name: data-volume
          mountPath: /app
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: discord-bot-data

