apiVersion: v1
kind: PersistentVolume
metadata:
  name: discord-bot-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: bot-data
          operator: In
          values:
          - true
  hostPath:
    path: /k8s/discord-bot-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-bot-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
