apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 1
  template:
    metadata:
      name: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: discord-bot
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
          requests:
            cpu: "200m"
            memory: "250Mi"
