apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-dev
spec:
  template:
    spec:
      containers:
      - name: discord-bot
        image: discord-bot
        volumeMounts:
        - name: config-volume
          mountPath: /app
        - name: secret-volume
          mountPath: /secret
      volumes:
      - name: config-volume
        secret:
          secretName: bot-config
      - name: secret-volume
        secret:
          secretName: discord-bot-secret
