pipeline {
    agent any
    stages {
        stage('Applying changes to container') {
            steps {
                sh "cp bot/* /k8s/discord-bot-data/"
                script {
                    withKubeConfig(credentialsId: 'kubeconfig') {
                        sh "kubectl apply -k k8s/"
                        sh "kubectl exec -n discord-bot-dev \$(kubectl get pod -n discord-bot-dev | cut -d ' ' -f1 | grep discord-bot-dev) -- kill -9 \$(pidof python3)"
                    }
                }
            }
        }
    }
}
